#!/bin/bash
# A script to automatically upload files to github

cd
cd Filepath
git commit -a -m "Daily Upload" -m "`$commitDate`"
git push https://Username:Password@github.com/Profile/Repository.git --all

wait